name: "Upload files to remote S3 server"
description: "This action uploads files that match a given regex to the remote S3 server"
branding:
  color: "red"
  icon: "box"
inputs:
  key:
    description: "S3 access key"
    required: true

  secret:
    description: "S3 secret key"
    required: true

  acl:
    description: "S3 ACL for the uploaded objects. Default: private."
    default: "private"
    required: false

  region:
    description: "S3 region"
    default: "us-east-1"
    required: false

  path_style:
    description: "Force S3 API to use path style. Default: true."
    default: "true"
    required: false

  endpoint:
    description: "address of the remote S3 server. I.e.: https://remote:8080"
    required: true

  bucket:
    description: "Remote S3 bucket where fields should be put into."
    required: true

  directory:
    description: "Directory with all the files to be uploaded"
    required: true

  prefix:
    description: "Prefix to be added to the destination file name. Default: none."
    required: false
    default: ""

  regex:
    description: "Regular expression to filter files. Only matches will be uploaded."
    required: false
    default: ""

  verbose:
    description: "print various messages during the upload. either \"true\" or \"false\""
    required: false
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"